"""Explicit local operations entrypoint. Run --help for subcommands."""
import argparse
import json
from pathlib import Path
import sys
sys.path.insert(0,str(Path(__file__).resolve().parent/'common'))
from pipeline_runtime import data,fit_oneclass,fit_supervised
from governance_runtime import Operations
import pandas as pd


def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--dataset',choices=['cn7','rg3'],required=True)
    p.add_argument('--state-root',type=Path,help='Isolated runtime root for rehearsal')
    p.add_argument('--min-recall',type=float,default=.5)
    p.add_argument('--min-precision',type=float,default=.2)
    p.add_argument('--max-fpr',type=float,default=.2)
    p.add_argument('--cn7-mode',choices=['budget','threshold'],default='budget',help='CN7 판정: 검사 예산(기본) 또는 고정 임계값')
    p.add_argument('--inspection-fraction',type=float,default=.1,help='배치당 검사 비율(검사 예산), 0 초과 1 이하. 최소 1개 검사')
    p.add_argument('--min-budget-capture',type=float,default=.5,help='평가 시 예산 내 최소 위험 발견 비율')
    p.add_argument('--rg3-history-triggers-recheck',action='store_true',help='RG3 구간 위험 이력만으로도 재검사 권고(기본: 참고 표시만)')
    p.add_argument('--cn7-tie-rule',choices=['exact_k','all_ties'],default='exact_k',
                   help='검사 예산 경계 동점 처리: exact_k(정확히 예산 수, record_id 순) 또는 all_ties(동점 전부, 예산 초과 기록)')
    sub=p.add_subparsers(dest='action',required=True)
    sub.add_parser('status');sub.add_parser('baseline');sub.add_parser('drift')
    sub.add_parser('pending',help='수집은 됐지만 감지·안내가 끝나지 않은 배치 목록')
    sub.add_parser('baseline-status',help='현재 기준선이 운영 모델·파일과 맞는지 읽기 전용 확인')
    sub.add_parser('reconcile-monitor',help='감지 기록은 있는데 소비 장부에 빠진 윈도를 한 번만 반영')
    sub.add_parser('resume-transition',help='미완료 모델/기준선 전환 재개')
    status=sub.add_parser('batch-status',help='배치 처리 상태·최신 감지·안내 이력 조회');status.add_argument('--batch-id',required=True)
    refresh=sub.add_parser('refresh-advice',help='실패한 후속 윈도 안내 갱신 재개');refresh.add_argument('--batch-id',required=True)
    resume=sub.add_parser('resume',help='수집 완료 배치의 미완료 단계(감지·안내)만 다시 실행');resume.add_argument('--batch-id',required=True)
    initial=sub.add_parser('initial');initial.add_argument('--kind',choices=['if','lr','rf'],required=True)
    activate=sub.add_parser('initialize');activate.add_argument('--version',required=True);activate.add_argument('--reason',required=True)
    batch=sub.add_parser('ingest');batch.add_argument('--input',type=Path,required=True)
    batch.add_argument('--batch-id');batch.add_argument('--label-source');batch.add_argument('--coordinates-confirmed',action='store_true')
    batch.add_argument('--production-time-column');batch.add_argument('--process-version');batch.add_argument('--metadata-source')
    ct=sub.add_parser('retrain');ct.add_argument('--kind',choices=['if','ocsvm','lr','rf'],required=True)
    ct.add_argument('--batch-ids',nargs='+',required=True);ct.add_argument('--drift-id',required=True);ct.add_argument('--cause',required=True)
    ct.add_argument('--approval-id',required=True)
    ev=sub.add_parser('register-evaluation');ev.add_argument('--input',type=Path,required=True)
    ev.add_argument('--label-source',required=True);ev.add_argument('--purpose',choices=['independent','historical_followup'],default='independent')
    ev.add_argument('--evaluation-id',help='등록 준비 실패 재개 시 최초 ID를 지정')
    sub.add_parser('evaluation-registration-status',help='실패 후 재개 가능한 평가 준비 목록')
    migration=sub.add_parser('migrate-evaluation',help='구형 평가 원본 보존 후 후속 평가 사본 이관')
    migration.add_argument('--evaluation-id',required=True);migration.add_argument('--label-source',required=True)
    migration.add_argument('--reason',required=True);migration.add_argument('--new-evaluation-id')
    compare=sub.add_parser('evaluate');compare.add_argument('--candidate',required=True);compare.add_argument('--evaluation-id',required=True)
    select=sub.add_parser('select-cn7');select.add_argument('--candidates',nargs=3,required=True);select.add_argument('--evaluation-id',required=True)
    deploy=sub.add_parser('promote');deploy.add_argument('--assessment-id',required=True)
    deploy.add_argument('--approval-id',required=True);deploy.add_argument('--product-validation-id')
    unlock=sub.add_parser('unlock');unlock.add_argument('--reason',required=True);unlock.add_argument('--force',action='store_true')
    unlock.add_argument('--lock',choices=['writer','ingest','operation'],default='writer',help='해제할 잠금(기본 writer)')
    undo=sub.add_parser('rollback');undo.add_argument('--kind',choices=['if','ocsvm','lr','rf'],required=True);undo.add_argument('--reason',required=True)
    undo.add_argument('--approval-id',required=True)
    sub.add_parser('governance-status')
    sub.add_parser('reference-status')
    config=sub.add_parser('configure-governance');config.add_argument('--settings-json',type=Path,required=True)
    config.add_argument('--actor',required=True);config.add_argument('--reason',required=True)
    approval=sub.add_parser('approve-action');approval.add_argument('--action-type',choices=['ct','promote','reference','rollback'],required=True)
    approval.add_argument('--payload-json',type=Path,required=True);approval.add_argument('--evidence-json',type=Path,required=True);approval.add_argument('--actor',required=True)
    products=sub.add_parser('product-validation');products.add_argument('--assessment-id',required=True)
    products.add_argument('--input',type=Path,required=True);products.add_argument('--label-source',required=True)
    reference=sub.add_parser('update-reference');reference.add_argument('--batch-ids',nargs='+',required=True)
    reference.add_argument('--reason',required=True);reference.add_argument('--approval-id',required=True)
    undo_ref=sub.add_parser('rollback-reference');undo_ref.add_argument('--reason',required=True);undo_ref.add_argument('--approval-id',required=True)
    a=p.parse_args()
    if not all(0<=v<=1 for v in [a.min_recall,a.min_precision,a.max_fpr,a.inspection_fraction,a.min_budget_capture]):p.error('성능 기준은 0~1이어야 합니다')
    if not 0<a.inspection_fraction<=1:p.error('검사 비율은 0 초과 1 이하여야 합니다(0%는 허용하지 않음: 최소 1개 검사)')
    ops=Operations(a.dataset,a.state_root,dict(min_recall=a.min_recall,min_precision=a.min_precision,max_FPR=a.max_fpr,rg3_history_triggers_recheck=a.rg3_history_triggers_recheck,
        cn7_decision_mode=a.cn7_mode,inspection_fraction=a.inspection_fraction,min_budget_capture=a.min_budget_capture,
        cn7_tie_rule=a.cn7_tie_rule))
    if a.action=='status':result=ops.registry()
    elif a.action=='baseline':result=ops.create_baseline()
    elif a.action=='drift':result=ops.detect()
    elif a.action=='pending':result=ops.pending_batches()
    elif a.action=='baseline-status':result=ops.baseline_status()
    elif a.action=='reconcile-monitor':result=dict(applied_drift_ids=ops.reconcile_monitor())
    elif a.action=='resume-transition':result=dict(version=ops.resume_transition())
    elif a.action=='batch-status':result=ops.batch_status(a.batch_id)
    elif a.action=='refresh-advice':result=ops.refresh_advice(a.batch_id)
    elif a.action=='resume':result=ops.resume(a.batch_id)
    elif a.action=='initialize':result=ops.initialize(a.version,a.reason)
    elif a.action=='initial':
        x,y,_,dev,_,_=data(a.dataset)
        b=fit_oneclass(a.dataset,x.loc[dev][y.loc[dev].eq(0)],'if') if a.kind=='if' else fit_supervised(a.dataset,x.loc[dev],y.loc[dev],kind=a.kind)
        result=ops.save_candidate(b,x.loc[dev],y.loc[dev],source={'kind':'fixed baseline; not grid-selected'})
    elif a.action=='ingest':result=ops.ingest(pd.read_csv(a.input,float_precision='round_trip',dtype={'record_id':str,'product_id':str}),a.batch_id,a.label_source,a.coordinates_confirmed,
                                            production_time_column=a.production_time_column,process_version=a.process_version,metadata_source=a.metadata_source)
    elif a.action=='retrain':result=ops.retrain(a.kind,a.batch_ids,a.drift_id,a.cause,approval_id=a.approval_id)
    elif a.action=='register-evaluation':result=ops.register_evaluation(pd.read_csv(a.input,float_precision='round_trip'),a.label_source,a.purpose,a.evaluation_id)
    elif a.action=='evaluation-registration-status':result=ops.evaluation_registration_status()
    elif a.action=='migrate-evaluation':result=ops.migrate_evaluation(a.evaluation_id,a.label_source,a.reason,a.new_evaluation_id)
    elif a.action=='evaluate':result=ops.evaluate(a.candidate,a.evaluation_id)
    elif a.action=='select-cn7':result=ops.select_cn7(a.candidates,a.evaluation_id)
    elif a.action=='unlock':result=ops.clear_lock(a.reason,a.force,a.lock)
    elif a.action=='promote':result=ops.promote(a.assessment_id,approval_id=a.approval_id,product_validation_id=a.product_validation_id)
    elif a.action=='rollback':result=ops.rollback(a.kind,a.reason,approval_id=a.approval_id)
    elif a.action=='governance-status':result=ops.governance_status()
    elif a.action=='reference-status':result=ops.reference_status()
    elif a.action=='configure-governance':result=ops.configure_governance(json.loads(a.settings_json.read_text(encoding='utf-8')),a.actor,a.reason)
    elif a.action=='approve-action':result=ops.approve_action(a.action_type,json.loads(a.payload_json.read_text(encoding='utf-8')),
                                                            json.loads(a.evidence_json.read_text(encoding='utf-8')),a.actor)
    elif a.action=='product-validation':result=ops.record_product_validation(a.assessment_id,pd.read_csv(a.input,float_precision='round_trip',dtype={'record_id':str,'product_id':str}),a.label_source)
    elif a.action=='update-reference':result=ops.update_reference(a.batch_ids,a.reason,approval_id=a.approval_id)
    else:result=ops.rollback_reference(a.reason,approval_id=a.approval_id)
    print(json.dumps(result,ensure_ascii=False,indent=2))


if __name__=='__main__':main()
